server:
  port: 8080
  shutdown: graceful

ai:
  url: http://localhost:11434
  model: deepseek-r1:8b
  embedding:
    prefix: "prefix:"
    index-name: "index"
  similarity:
    threshold: 0.9
    top-k: 3
  splitter:
    chunk-size: 1000
    min-chars: 80
    min-tokens: 8
    max-chunks: 300
    keep-separator: false

spring:
  application:
    name: ai
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: local
      base-url: ${ai.url}
      chat:
        options:
          model: ${ai.model}
      embedding:
        base-url: ${ai.url}
        options:
          model: ${ai.model}
    vectorstore:
      redis:
        uri: redis://${spring.data.redis.username}:${spring.data.redis.password}@${spring.data.redis.host}:${spring.data.redis.port}
        prefix: "embedding:"
        index-name: "spring-ai-index"
  data:
    redis:
      host: localhost
      port: 6379
      username: test
      password: test
      database: 0
      client-name: test
      ssl:
        enabled: false
      url: redis://${spring.data.redis.username}:${spring.data.redis.password}@${spring.data.redis.host}:${spring.data.redis.port}
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 4
      idle-timeout: 10000
      max-lifetime: 300000
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yaml
