server:
  port: 8080
  shutdown: graceful

ai:
  url: http://localhost:11434
  model: deepseek-r1:8b

spring:
  application:
    name: ai
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: local
      base-url: ${ai.url}
      chat:
        options:
          model: ${ai.model}
      embedding:
        base-url: ${ai.url}
        options:
          model: ${ai.model}
    vectorstore:
      redis:
        uri: redis://${spring.data.redis.username}:${spring.data.redis.password}@${spring.data.redis.host}:${spring.data.redis.port}
        prefix: "embedding:"
        index-name: "spring-ai-index"
  data:
    redis:
      host: localhost
      port: 6379
      username: test
      password: test
      database: 0
      client-name: test
      ssl:
        enabled: false
      url: redis://${spring.data.redis.username}:${spring.data.redis.password}@${spring.data.redis.host}:${spring.data.redis.port}
